import React, { useState } from 'react';
import { Sparkles, Loader2, BookOpen, Layers, Edit3 } from 'lucide-react';
import { generateFlashcardsFromTopic } from '../services/geminiService';
import { Deck, Flashcard, GenerateStatus } from '../types';

interface DeckCreatorProps {
  onDeckCreated: (deck: Deck) => void;
  onCancel: () => void;
}

export const DeckCreator: React.FC<DeckCreatorProps> = ({ onDeckCreated, onCancel }) => {
  const [topic, setTopic] = useState('');
  const [count, setCount] = useState(5);
  const [status, setStatus] = useState<GenerateStatus>('idle');
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!topic.trim()) return;

    setStatus('generating');
    setError(null);

    try {
      const rawCards = await generateFlashcardsFromTopic(topic, count);
      
      const newCards: Flashcard[] = rawCards.map((card) => ({
        ...card,
        id: crypto.randomUUID(),
        mastered: false,
      }));

      const newDeck: Deck = {
        id: crypto.randomUUID(),
        title: topic,
        description: `${newCards.length} cards generated by AI`,
        cards: newCards,
        createdAt: Date.now(),
        themeColor: 'indigo',
        icon: 'book',
      };

      setStatus('success');
      setTimeout(() => {
        onDeckCreated(newDeck);
      }, 500);

    } catch (err) {
      console.error(err);
      setStatus('error');
      setError("Failed to generate cards. Please check your API key or try a different topic.");
    }
  };

  const handleCreateManual = () => {
    // Create an empty template deck
    const emptyDeck: Deck = {
      id: crypto.randomUUID(),
      title: "New Deck",
      description: "Custom created deck",
      cards: [
        { id: crypto.randomUUID(), front: "", back: "", mastered: false },
        { id: crypto.randomUUID(), front: "", back: "", mastered: false },
        { id: crypto.randomUUID(), front: "", back: "", mastered: false }
      ],
      createdAt: Date.now(),
      themeColor: 'emerald',
      icon: 'edit',
    };
    onDeckCreated(emptyDeck);
  };

  return (
    <div className="max-w-xl mx-auto px-4 py-8 animate-fade-in">
      <div className="bg-white rounded-2xl shadow-lg border border-slate-100 p-8">
        <div className="flex items-center gap-3 mb-6 text-indigo-600">
          <Sparkles className="w-8 h-8" />
          <h2 className="text-2xl font-bold text-slate-800">Create New Deck</h2>
        </div>

        <div className="space-y-6">
          <div>
            <label className="block text-sm font-medium text-slate-700 mb-2">
              Topic (for AI Generation)
            </label>
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              placeholder="e.g., Photosynthesis, Spanish Verbs..."
              className="w-full px-4 py-3 rounded-xl border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 outline-none transition-all text-slate-800 placeholder:text-slate-400"
              disabled={status === 'generating'}
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-700 mb-2">
              Number of Cards
            </label>
            <div className="grid grid-cols-3 gap-3">
              {[5, 10, 15].map((num) => (
                <button
                  key={num}
                  onClick={() => setCount(num)}
                  disabled={status === 'generating'}
                  className={`py-2 rounded-lg text-sm font-medium transition-colors ${
                    count === num
                      ? 'bg-indigo-600 text-white'
                      : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                  }`}
                >
                  {num} Cards
                </button>
              ))}
            </div>
          </div>

          {error && (
            <div className="p-4 bg-red-50 text-red-600 rounded-lg text-sm">
              {error}
            </div>
          )}

          <div className="pt-4 flex flex-col gap-3">
            <div className="flex gap-4">
              <button
                onClick={onCancel}
                disabled={status === 'generating'}
                className="flex-1 py-3 px-4 rounded-xl text-slate-600 font-medium hover:bg-slate-50 transition-colors"
              >
                Cancel
              </button>
              <button
                onClick={handleGenerate}
                disabled={status === 'generating' || !topic.trim()}
                className="flex-1 py-3 px-4 rounded-xl bg-indigo-600 text-white font-medium hover:bg-indigo-700 active:transform active:scale-95 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex justify-center items-center gap-2 shadow-lg shadow-indigo-200"
              >
                {status === 'generating' ? (
                  <>
                    <Loader2 className="w-5 h-5 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="w-5 h-5" />
                    Generate with AI
                  </>
                )}
              </button>
            </div>
            
            <div className="relative my-2">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-slate-200"></div>
              </div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-white px-2 text-slate-400">Or</span>
              </div>
            </div>

            <button
              onClick={handleCreateManual}
              disabled={status === 'generating'}
              className="w-full py-3 px-4 rounded-xl border border-slate-300 text-slate-600 font-medium hover:bg-slate-50 hover:text-slate-800 transition-colors flex items-center justify-center gap-2"
            >
              <Edit3 className="w-4 h-4" />
              Create Manually
            </button>
          </div>
        </div>
      </div>
      
      <div className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-4 text-slate-500 text-sm">
        <div className="flex items-start gap-3 p-4 bg-white/50 rounded-xl">
          <Layers className="w-5 h-5 mt-0.5 text-indigo-400" />
          <p>Instant deck creation using Gemini AI models for accurate summaries.</p>
        </div>
        <div className="flex items-start gap-3 p-4 bg-white/50 rounded-xl">
          <Edit3 className="w-5 h-5 mt-0.5 text-indigo-400" />
          <p>Or create your own deck from scratch and customize every card.</p>
        </div>
      </div>
    </div>
  );
};